INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (1,'Agumon', 'Feb 3, 2020', 10.23, TRUE, 0);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (2,'Gabumon', 'Nov 15, 2018', 8, TRUE, 2);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (3,'Pikachu', 'Jan 7, 2021', 15.04, FALSE, 1);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (4,'Devimon', 'May 12, 2017', 11, TRUE, 5);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (5,'Charmander', '08/02/2020', 0, FALSE, -11.0);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (6,'Plantmon', '15/11/2021', 2, TRUE, -5.7);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (7,'Squirtle', '02/04/1993', 3, FALSE, -12.13);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (8,'Angemon', '12/06/2005', 1, TRUE, -45.0);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (9,'Boarmon', '07/06/2005', 7, TRUE, 20.4);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (10,'Blossom', '13/10/1998', 3, TRUE, 17.0);
INSERT INTO animals (id,name, date_of_birth, weight_kg, neutered, escape_attempts) VALUES (11,'Ditto', '14/05/2022', 4, TRUE, 22.0);
